---
- name: Load vault secrets
  ansible.builtin.include_vars:
    file: secrets.yml
- name: Install MySQL
  ansible.builtin.apt:
    name: mysql-server
    state: present
    update_cache: true
- name: Ensure MySQL is running
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: true
- name: Show db name (using vault variable)
  ansible.builtin.debug:
    msg: "Database name is {{ db_name }}"
