---
- name: Load vault secrets
  include_vars: secrets.yml

- name: Install MySQL
  apt:
    name: mysql-server
    state: present
    update_cache: yes

- name: Ensure MySQL is running
  service:
    name: mysql
    state: started
    enabled: yes

- name: Show db name (using vault variable)
  debug:
    msg: "Database name is {{ db_name }}"
