name: Ansible CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ansible-lint:
    name: Lint Playbook
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Ansible
        run: |
          pip install ansible ansible-lint

      - name: Run Ansible Lint
        run: |
          cd ansible-project
          ansible-lint playbook.yml
        continue-on-error: true

  ansible-check:
    name: Dry Run
    runs-on: ubuntu-latest
    needs: ansible-lint

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Ansible
        run: |
          pip install ansible

      - name: Run Syntax Check
        run: |
          cd ansible-project
          ansible-playbook \
            -i inventory-ci.yml \
            playbook.yml \
            --syntax-check

      - name: Pipeline Finished
        run: echo "CI/CD pipeline finished successfully."
